// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }





// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { Playfair_Display } from "next/font/google"; // 1. Import the new font
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // 2. Configure the new font
// const playfair = Playfair_Display({
//   variable: '--font-playfair',
//   subsets: ['latin'],
//   weight: ['700', '900'] // Use bold weights
// });

// export const metadata: Metadata = {
//   title: "Sentinel.ai",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     // 3. Add the new font variable here
//     <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable}`}>
//       <body className="antialiased">
//         {children}
//       </body>
//     </html>
//   );
// }





'use client';


import { useState } from "react";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { Playfair_Display } from "next/font/google";
import SentinelLoader from "../app/home/SentinelLoader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: '--font-playfair',
  subsets: ['latin'],
  weight: ['700', '900']
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [ready, setReady] = useState(false);

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable}`}>
      <body className="antialiased">
        {!ready ? <SentinelLoader onReady={() => setReady(true)} /> : children}
      </body>
    </html>
  );
}
